### ISSUE TITLE
raspion is not updatable

### ISSUE THREAD

**Issue by mok-liee** [ct-Open-Source/ctraspion#8]
hello ct team,

I try to update my rasping 104 to 107 but after hitting ./install.sh I get

```
pi@raspion:~/raspion $ ./install.sh 
==> Einrichtung des c't-Raspion (v107)                                                                                                         
* Wifi einschalten                                                                                                                             
* Hilfspakete hinzufügen, Paketlisten aktualisieren                                                                                            
* Firewallregeln vorbereiten, Module laden                                                                                                     
* Pakete vorkonfigurieren ...                                                                                                                  
* Firewall-Regeln speichern ...                                                                                                                
Installation leider fehlgeschlagen in Zeile 50
```

 and the install2.sh is not in the zip bundle!

**Comment by Diggen85** [comment]
Hi,
the Script is just for a complete install. One part is setup a repository. So an apt update && apt full-upgrade will update the system and raspion.
But dont expect anything new. The releases are just fixes for the install script. And the included install.sh is the install2.sh. The c't build server package this into the release zip.

 Actually I have not much time to work on raspion because of corona, my job as a IT-Admin in a hospital is actually more than fulltime...
I dont know how it looks at the c't office but I think they have not much time too :-(

Benn

Von meinem iPhone gesendet

Am 16.03.2020 um 01:40 schrieb mok <notifications@github.com>:

﻿

hello ct team,

I try to update my rasping 104 to 107 but after hitting ./install.sh I get

pi@raspion:~/raspion $ ./install.sh
==> Einrichtung des c't-Raspion (v107)
* Wifi einschalten
* Hilfspakete hinzufügen, Paketlisten aktualisieren
* Firewallregeln vorbereiten, Module laden
* Pakete vorkonfigurieren ...
* Firewall-Regeln speichern ...
Installation leider fehlgeschlagen in Zeile 50


and the install2.sh is not in the zip bundle!
